spring:
  application:
    name: hahn

  datasource:
    url: jdbc:postgresql://localhost:5432/hahn
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  error:
    include-message: always
    include-binding-errors: always